### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by despeset** [despeset/glitz.js#1]
Here's a rough todo for now:
- [ ] tests!
- [ ] documentation with examples for danielmendel.github.com/glitz.js
- [ ] move the rest of animation loop to `requestAnimationFrame`
- [x] further optimize & reduce lib size ( 2e5cbb7d41d7fe15e965adc2c9647f297aa0a3e1 )
- [ ] turn this list into individual issues
- [ ] add build script 
- [ ] add a `noConflict` method for due diligence
